# =============================================================================
# 帮助信息
# =============================================================================

.PHONY: help

# 显示帮助信息
help:
	@echo "$(CYAN)=== Python MiniBlog Makefile 帮助 ===$(RESET)"
	@echo ""
	@echo "$(YELLOW)开发环境:$(RESET)"
	@echo "  setup                - 安装依赖和初始化项目"
	@echo "  init-db              - 初始化MySQL数据库"
	@echo "  dev                  - 启动单体应用开发服务器"
	@echo "  dev-microservices    - 启动微服务开发环境"
	@echo "  dev-stop             - 停止微服务开发环境"
	@echo "  dev-setup            - 开发环境完整设置"
	@echo "  microservices-setup  - 微服务架构设置"
	@echo ""
	@echo "$(YELLOW)测试和质量:$(RESET)"
	@echo "  test                 - 运行所有测试"
	@echo "  test-unit            - 运行单元测试"
	@echo "  test-integration     - 运行集成测试"
	@echo "  test-api             - 测试API接口（默认环境）"
	@echo "  test-api-dev         - 测试API接口（开发环境）"
	@echo "  lint                 - 代码检查"
	@echo "  format               - 代码格式化"
	@echo "  clean                - 清理临时文件"
	@echo ""
	@echo "$(YELLOW)Docker:$(RESET)"
	@echo "  docker-build-images  - 构建所有微服务Docker镜像"
	@echo "  docker-build-user    - 构建用户服务Docker镜像"
	@echo "  docker-build-blog    - 构建博客服务Docker镜像"
	@echo "  docker-run           - 启动微服务Docker环境"
	@echo "  docker-stop          - 停止微服务Docker环境"
	@echo "  docker-clean         - 清理Docker资源"
	@echo "  docker-images        - 显示项目相关Docker镜像"
	@echo "  docker-push          - 推送Docker镜像到仓库"
	@echo ""
	@echo "$(YELLOW)Kind集群:$(RESET)"
	@echo "  kind-create          - 创建Kind集群"
	@echo "  kind-delete          - 删除Kind集群"
	@echo "  kind-load-images     - 构建并加载镜像到Kind集群"
	@echo "  kind-deploy          - 完整的Kind部署流程"

	@echo "  helm-lint            - 验证Helm Chart"
	@echo "  helm-package         - 打包Helm Chart"
	@echo ""
	@echo "$(YELLOW)工具和信息:$(RESET)"
	@echo "  status               - 显示项目状态"
	@echo "  help                 - 显示此帮助信息"
	@echo ""
	@echo "$(YELLOW)快速开始:$(RESET)"
	@echo "  $(GREEN)1.$(RESET) make setup        - 安装依赖和初始化项目"
	@echo "  $(GREEN)2.$(RESET) make init-db      - 初始化数据库"
	@echo "  $(GREEN)3.$(RESET) make kind-deploy  - 创建Kind集群并部署应用"
	@echo "  $(GREEN)4.$(RESET) make test-api     - 测试API接口"
	@echo ""
	@echo "$(YELLOW)环境变量:$(RESET)"
	@echo "  DOCKER_REGISTRY      - Docker镜像仓库地址（用于推送镜像）"
	@echo "  VERSION              - 镜像版本标签（默认: git describe）"
	@echo ""
	@echo "$(YELLOW)目录结构:$(RESET)"
	@echo "  scripts/make-rules/  - Make规则模块"
	@echo "  manifests/helm/      - Helm Chart文件（按环境区分）"
	@echo "  manifests/kubernetes/ - Kubernetes配置文件"
	@echo "  manifests/env/       - 环境配置文件"