# Default values for python-miniblog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: miniblog
  imageRegistry: ""
  imagePullSecrets: []

# ConfigMap for application configuration
configMap:
  enabled: true


# User Service
userService:
  enabled: true
  replicaCount: 2
  image:
    repository: python-miniblog-user
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    DATABASE_URL: "mysql+pymysql://miniblog:miniblog123@python-miniblog-mysql:3306/miniblog"
    REDIS_HOST: "python-miniblog-redis"
    REDIS_PORT: "6379"
    REDIS_DB: "0"
    NACOS_HOST: "python-miniblog-nacos"
    NACOS_PORT: "8848"
    NACOS_NAMESPACE: "public"
    NACOS_USERNAME: "nacos"
    NACOS_PASSWORD: "nacos"
    SERVICE_NAME: "user-service"
    SERVICE_IP: "python-miniblog-user"
    SERVICE_PORT: "5001"
    JWT_SECRET_KEY: "your-secret-key-here"
    JWT_ALGORITHM: "HS256"
    SECRET_KEY: "your-secret-key-here"
  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3

# Blog Service
blogService:
  enabled: true
  replicaCount: 2
  image:
    repository: python-miniblog-blog
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5002
    targetPort: 5002
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  # Environment variables are now managed via ConfigMap
  # Only service-specific variables remain here if needed
  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3

# MySQL Database (optional)
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: "root123"
    username: "miniblog"
    password: "miniblog123"
    database: "miniblog"
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Redis Cache (optional)
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    size: 4Gi
    storageClass: ""
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Ingress
ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: python-miniblog.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-miniblog-tyk-gateway
              port:
                number: 8080
  tls: []

# Nacos Service Registry (Disabled - using Kubernetes native service discovery)
nacos:
  enabled: false
  image:
    repository: nacos/nacos-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8848
  env:
    # Registry only mode - no database required
    MODE: "standalone"
    NACOS_AUTH_ENABLE: "false"
    NACOS_AUTH_TOKEN: "SecretKey012345678901234567890123456789012345678901234567890123456789"
    NACOS_AUTH_IDENTITY_KEY: "serverIdentity"
    NACOS_AUTH_IDENTITY_VALUE: "security"
    # Disable config center features
    NACOS_CONFIG_MIGRATE_ENABLED: "false"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Tyk API Gateway
tyk:
  enabled: true
  gateway:
    image:
      repository: tykio/tyk-gateway
      tag: v5.2.3
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    env:
      TYK_GW_SECRET: "352d20ee67be67f6340b4c0605b044b7"
      TYK_GW_STORAGE_TYPE: "redis"
      TYK_GW_STORAGE_HOST: "python-miniblog-redis"
      TYK_GW_STORAGE_PORT: "6379"
      TYK_GW_STORAGE_DATABASE: "1"
      TYK_GW_ENABLEANALYTICS: "false"
      TYK_GW_ANALYTICSCONFIG_TYPE: ""
      TYK_GW_HTTPSERVEROPTIONS_USESSL: "false"
      TYK_GW_HTTPSERVEROPTIONS_CERTIFICATES: ""
      TYK_GW_HTTPSERVEROPTIONS_SSLINSECURESKIPVERIFY: "true"
      TYK_GW_LOGLEVEL: "info"
      TYK_GW_POLICIES_POLICY_SOURCE: "file"
      TYK_GW_POLICIES_POLICY_PATH: "/opt/tyk-gateway/policies"
      TYK_GW_APP_PATH: "/opt/tyk-gateway/apps"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  dashboard:
    enabled: false

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Security Context
podSecurityContext: {}

# Security Context
securityContext: {}

# Node Selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}