{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-miniblog.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
data:
  # Database Configuration
  DATABASE_URL: "mysql+pymysql://miniblog:miniblog123@python-miniblog-mysql:3306/miniblog"
  
  # Redis Configuration
  REDIS_HOST: "python-miniblog-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # JWT Configuration
  JWT_SECRET_KEY: "your-secret-key-here"
  JWT_ALGORITHM: "HS256"
  SECRET_KEY: "your-secret-key-here"
  
  # Application Configuration
  POSTS_PER_PAGE: "10"
  MAX_POSTS_PER_PAGE: "50"
  CACHE_DEFAULT_TIMEOUT: "300"
  USER_SERVICE_TIMEOUT: "10"
  
  # Service Configuration
  USER_SERVICE_URL: "http://python-miniblog-user:5001"
  BLOG_SERVICE_URL: "http://python-miniblog-blog:5002"
{{- end }}