{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-miniblog.fullname" . }}-user
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-miniblog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: user-service
  template:
    metadata:
      labels:
        {{- include "python-miniblog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: user-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "python-miniblog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: user-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.userService.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.userService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.userService.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.userService.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.userService.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.userService.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.userService.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.userService.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.userService.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.userService.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- if .Values.blogService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-miniblog.fullname" . }}-blog
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: blog-service
spec:
  replicas: {{ .Values.blogService.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-miniblog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: blog-service
  template:
    metadata:
      labels:
        {{- include "python-miniblog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: blog-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "python-miniblog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: blog-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.blogService.image.repository }}:{{ .Values.blogService.image.tag }}"
          imagePullPolicy: {{ .Values.blogService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.blogService.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.blogService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.blogService.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.blogService.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.blogService.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.blogService.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.blogService.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.blogService.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.blogService.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.blogService.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.blogService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}