{{- if .Values.nacos.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-miniblog.fullname" . }}-nacos
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "python-miniblog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nacos
  template:
    metadata:
      labels:
        {{- include "python-miniblog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nacos
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nacos
          image: "{{ .Values.global.imageRegistry }}{{ .Values.nacos.image.repository }}:{{ .Values.nacos.image.tag }}"
          imagePullPolicy: {{ .Values.nacos.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8848
              protocol: TCP
          env:
            {{- range $key, $value := .Values.nacos.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.nacos.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-miniblog.fullname" . }}-nacos
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: nacos
spec:
  type: {{ .Values.nacos.service.type }}
  ports:
    - port: {{ .Values.nacos.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "python-miniblog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nacos
{{- end }}