{{- if .Values.tyk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-miniblog.fullname" . }}-tyk-api-definition
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: tyk-gateway
data:
  api-definition.json: |
    {
      "name": "Python MiniBlog User Service",
      "slug": "user-service",
      "api_id": "user-service",
      "org_id": "default",
      "use_keyless": false,
      "use_standard_auth": true,
      "auth": {
        "auth_header_name": "Authorization",
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": ""
      },
      "definition": {
        "location": "header",
        "key": "version"
      },
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true,
            "extended_paths": {
              "ignored": [
                {
                  "path": "/api/auth/login",
                  "method_actions": {"POST": {"action": "no_action"}}
                },
                {
                  "path": "/api/auth/register",
                  "method_actions": {"POST": {"action": "no_action"}}
                },
                {
                  "path": "/healthz",
                  "method_actions": {"GET": {"action": "no_action"}}
                }
              ]
            }
          }
        }
      },
      "proxy": {
        "listen_path": "/api/users/",
        "target_url": "http://{{ include \"python-miniblog.fullname\" . }}-user:5001",
        "strip_listen_path": true
      },
      "active": true,
      "enable_cors": true,
      "cors": {
        "enable": true,
        "allowed_origins": ["*"],
        "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "allowed_headers": ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"]
      }
    }
  blog-api-definition.json: |
    {
      "name": "Python MiniBlog Blog Service",
      "slug": "blog-service",
      "api_id": "blog-service",
      "org_id": "default",
      "use_keyless": false,
      "use_standard_auth": true,
      "auth": {
        "auth_header_name": "Authorization",
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": ""
      },
      "definition": {
        "location": "header",
        "key": "version"
      },
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true,
            "extended_paths": {
              "ignored": [
                {
                  "path": "/healthz",
                  "method_actions": {"GET": {"action": "no_action"}}
                }
              ]
            }
          }
        }
      },
      "proxy": {
        "listen_path": "/api/posts/",
        "target_url": "http://{{ include \"python-miniblog.fullname\" . }}-blog:5002",
        "strip_listen_path": true
      },
      "active": true,
      "enable_cors": true,
      "cors": {
        "enable": true,
        "allowed_origins": ["*"],
        "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "allowed_headers": ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"]
      }
    }
  auth-api-definition.json: |
    {
      "name": "Python MiniBlog Auth Service",
      "slug": "auth-service",
      "api_id": "auth-service",
      "org_id": "default",
      "use_keyless": true,
      "definition": {
        "location": "header",
        "key": "version"
      },
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true
          }
        }
      },
      "proxy": {
        "listen_path": "/api/auth/",
        "target_url": "http://{{ include \"python-miniblog.fullname\" . }}-user:5001",
        "strip_listen_path": true
      },
      "active": true,
      "enable_cors": true,
      "cors": {
        "enable": true,
        "allowed_origins": ["*"],
        "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "allowed_headers": ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"]
      }
    }
{{- end }}