{{- if .Values.tyk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-miniblog.fullname" . }}-tyk-api-definition
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "python-miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: tyk-gateway
data:
  api-definition.json: |
    {
      "user-service": {
        "id": "user-service",
        "name": "Python MiniBlog User Service",
        "slug": "user-service",
        "api_id": "user-service",
        "org_id": "default",
        "use_keyless": false,
        "use_oauth2": false,
        "use_openid": false,
        "openid_options": {
          "providers": [],
          "segregate_by_client": false
        },
        "oauth_meta": {
          "allowed_access_types": [],
          "allowed_authorize_types": [],
          "auth_login_redirect": ""
        },
        "auth": {
          "use_param": false,
          "param_name": "",
          "use_cookie": false,
          "cookie_name": "",
          "auth_header_name": "Authorization",
          "use_certificate": false
        },
        "use_basic_auth": false,
        "basic_auth": {
          "disable_caching": false,
          "cache_ttl": 0,
          "extract_from_body": false,
          "body_user_regexp": "",
          "body_password_regexp": ""
        },
        "use_mutual_tls_auth": false,
        "client_certificates": [],
        "upstream_certificates": {},
        "pinned_public_keys": {},
        "enable_jwt": true,
        "jwt_signing_method": "hmac",
        "jwt_source": "header:Authorization",
        "jwt_identity_base_field": "user_id",
        "jwt_client_base_field": "",
        "jwt_policy_field_name": "pol",
        "jwt_default_policies": ["jwt_policy"],
        "jwt_issued_at_validation_skew": 0,
        "jwt_expires_at_validation_skew": 0,
        "jwt_not_before_validation_skew": 0,
        "jwt_skip_kid": false,
        "jwt_scope_to_policy_mapping": {},
        "jwt_scope_claim_name": "",
        "notifications": {
          "shared_secret": "",
          "oauth_on_keychange_url": ""
        },
        "enable_signature_checking": false,
        "hmac_allowed_clock_skew": -1,
        "hmac_allowed_algorithms": [],
        "request_signing": {
          "is_enabled": false
        },
        "base_identity_provided_by": "",
        "definition": {
          "location": "header",
          "key": "x-api-version",
          "strip_path": false
        },
        "version_data": {
          "not_versioned": true,
          "default_version": "",
          "versions": {
            "Default": {
              "name": "Default",
              "expires": "",
              "paths": {
                "ignored": [],
                "white_list": [],
                "black_list": []
              },
              "use_extended_paths": true,
              "extended_paths": {},
              "global_headers": {},
              "global_headers_remove": [],
              "global_response_headers": {},
              "global_response_headers_remove": [],
              "ignore_endpoint_case": false,
              "global_size_limit": 0,
              "override_target": ""
            }
          }
        },
        "proxy": {
          "preserve_host_header": false,
          "listen_path": "/api/v1/users/",
          "target_url": "http://python-miniblog-user:5001/",
          "disable_strip_slash": true,
          "strip_listen_path": true,
          "enable_load_balancing": false,
          "target_list": [],
          "check_host_against_uptime_tests": false,
          "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "cache_timeout": 60
          },
          "transport": {
            "ssl_insecure_skip_verify": false,
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "ssl_force_common_name_check": false,
            "proxy_url": ""
          }
        },
        "disable_rate_limit": false,
        "disable_quota": false,
        "custom_middleware": {
          "pre": [],
          "post": [],
          "post_key_auth": [],
          "auth_check": {
            "name": "",
            "path": "",
            "require_session": false,
            "raw_body_only": false
          },
          "response": [],
          "driver": "",
          "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
          }
        },
        "custom_middleware_bundle": "",
        "cache_options": {
          "cache_timeout": 60,
          "enable_cache": true,
          "cache_all_safe_requests": false,
          "cache_response_codes": [],
          "enable_upstream_cache_control": false,
          "cache_control_ttl_header": "",
          "cache_by_headers": []
        },
        "session_lifetime": 0,
        "active": true,
        "auth_provider": {
          "name": "",
          "storage_engine": "",
          "meta": {}
        },
        "session_provider": {
          "name": "",
          "storage_engine": "",
          "meta": {}
        },
        "event_handlers": {
          "events": {}
        },
        "enable_batch_request_support": false,
        "enable_ip_whitelisting": false,
        "allowed_ips": [],
        "enable_ip_blacklisting": false,
        "blacklisted_ips": [],
        "dont_set_quota_on_create": false,
        "expire_analytics_after": 0,
        "response_processors": [],
        "CORS": {
          "enable": true,
          "allowed_origins": ["*"],
          "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
          "allowed_headers": ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"],
          "exposed_headers": [],
          "allow_credentials": false,
          "max_age": 24,
          "options_passthrough": false,
          "debug": false
        },
        "domain": "",
        "certificates": [],
        "do_not_track": false,
        "tags": ["user-service", "api"],
        "enable_context_vars": false,
        "config_data": {},
        "tag_headers": [],
        "global_rate_limit": {
          "rate": 0,
          "per": 0
        },
        "strip_auth_data": false
      },
      "blog-service": {
        "id": "blog-service",
        "name": "Python MiniBlog Blog Service",
        "slug": "blog-service",
        "api_id": "blog-service",
        "org_id": "default",
        "use_keyless": false,
        "use_oauth2": false,
        "use_openid": false,
        "openid_options": {
          "providers": [],
          "segregate_by_client": false
        },
        "oauth_meta": {
          "allowed_access_types": [],
          "allowed_authorize_types": [],
          "auth_login_redirect": ""
        },
        "auth": {
          "use_param": false,
          "param_name": "",
          "use_cookie": false,
          "cookie_name": "",
          "auth_header_name": "Authorization",
          "use_certificate": false
        },
        "use_basic_auth": false,
        "basic_auth": {
          "disable_caching": false,
          "cache_ttl": 0,
          "extract_from_body": false,
          "body_user_regexp": "",
          "body_password_regexp": ""
        },
        "use_mutual_tls_auth": false,
        "client_certificates": [],
        "upstream_certificates": {},
        "pinned_public_keys": {},
        "enable_jwt": true,
        "jwt_signing_method": "hmac",
        "jwt_source": "header:Authorization",
        "jwt_identity_base_field": "user_id",
        "jwt_client_base_field": "",
        "jwt_policy_field_name": "pol",
        "jwt_default_policies": ["jwt_policy"],
        "jwt_issued_at_validation_skew": 0,
        "jwt_expires_at_validation_skew": 0,
        "jwt_not_before_validation_skew": 0,
        "jwt_skip_kid": false,
        "jwt_scope_to_policy_mapping": {},
        "jwt_scope_claim_name": "",
        "notifications": {
          "shared_secret": "",
          "oauth_on_keychange_url": ""
        },
        "enable_signature_checking": false,
        "hmac_allowed_clock_skew": -1,
        "hmac_allowed_algorithms": [],
        "request_signing": {
          "is_enabled": false
        },
        "base_identity_provided_by": "",
        "definition": {
          "location": "header",
          "key": "x-api-version",
          "strip_path": false
        },
        "version_data": {
          "not_versioned": true,
          "default_version": "",
          "versions": {
            "Default": {
              "name": "Default",
              "expires": "",
              "paths": {
                "ignored": [],
                "white_list": [],
                "black_list": []
              },
              "use_extended_paths": true,
              "extended_paths": {},
              "global_headers": {},
              "global_headers_remove": [],
              "global_response_headers": {},
              "global_response_headers_remove": [],
              "ignore_endpoint_case": false,
              "global_size_limit": 0,
              "override_target": ""
            }
          }
        },
        "proxy": {
          "preserve_host_header": false,
          "listen_path": "/api/v1/posts/",
          "target_url": "http://python-miniblog-blog:5002/",
          "disable_strip_slash": true,
          "strip_listen_path": true,
          "enable_load_balancing": false,
          "target_list": [],
          "check_host_against_uptime_tests": false,
          "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "cache_timeout": 60
          },
          "transport": {
            "ssl_insecure_skip_verify": false,
            "ssl_ciphers": [],
            "ssl_min_version": 0,
            "ssl_force_common_name_check": false,
            "proxy_url": ""
          }
        },
        "disable_rate_limit": false,
        "disable_quota": false,
        "custom_middleware": {
          "pre": [],
          "post": [],
          "post_key_auth": [],
          "auth_check": {
            "name": "",
            "path": "",
            "require_session": false,
            "raw_body_only": false
          },
          "response": [],
          "driver": "",
          "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
          }
        },
        "custom_middleware_bundle": "",
        "cache_options": {
          "cache_timeout": 60,
          "enable_cache": true,
          "cache_all_safe_requests": false,
          "cache_response_codes": [],
          "enable_upstream_cache_control": false,
          "cache_control_ttl_header": "",
          "cache_by_headers": []
        },
        "session_lifetime": 0,
        "active": true,
        "auth_provider": {
          "name": "",
          "storage_engine": "",
          "meta": {}
        },
        "session_provider": {
          "name": "",
          "storage_engine": "",
          "meta": {}
        },
        "event_handlers": {
          "events": {}
        },
        "enable_batch_request_support": false,
        "enable_ip_whitelisting": false,
        "allowed_ips": [],
        "enable_ip_blacklisting": false,
        "blacklisted_ips": [],
        "dont_set_quota_on_create": false,
        "expire_analytics_after": 0,
        "response_processors": [],
        "CORS": {
          "enable": true,
          "allowed_origins": ["*"],
          "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
          "allowed_headers": ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization"],
          "exposed_headers": [],
          "allow_credentials": false,
          "max_age": 24,
          "options_passthrough": false,
          "debug": false
        },
        "domain": "",
        "certificates": [],
        "do_not_track": false,
        "tags": ["blog-service", "api"],
        "enable_context_vars": false,
        "config_data": {},
        "tag_headers": [],
        "global_rate_limit": {
          "rate": 0,
          "per": 0
        },
        "strip_auth_data": false
      }
    }
{{- end }}